### ISSUE TITLE
Upgrade needed

### ISSUE THREAD

**Issue by budgierless** [Jan-E/php7-ffmpeg#14]
hi, 
Is their any chance you could update the code to support php8.3? as i have problems trying to make its build on ubuntu 24.04.
Thanks

**Comment by Jan-E** [comment]
The Windows version with FFmpeg 4.4.4 already works on PHP 8.3.6. See https://phpdev.toolsforresearch.com/php-8.3.6-nts-Win32-vs16-x64.htm 
What is the error message you are getting?

**Comment by budgierless** [comment]
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_stream_index’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:220:17: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
                 GET_CODEC_FIELD(fmt_ctx->streams[i]->codec, codec_type) == type) {
                 ^~~~~~~~~~~~~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:38:0:
/usr/local/cpffmpeg/include/libavformat/avformat.h:885:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_filename’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:268:32: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘filename’
     return ffmovie_ctx->fmt_ctx->filename;
                                ^~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie___construct’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:351:9: warning: variable ‘persistent’ set but not used [-Wunused-but-set-variable]
     int persistent = 0;
         ^~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_decoder_context’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:537:9: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
         decoder = avcodec_find_decoder(GET_CODEC_FIELD(
         ^~~~~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:38:0:
/usr/local/cpffmpeg/include/libavformat/avformat.h:885:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:548:13: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
             GET_CODEC_PTR(ffmovie_ctx->fmt_ctx->streams[stream_index]->codec);
             ^~~~~~~~~~~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:38:0:
/usr/local/cpffmpeg/include/libavformat/avformat.h:885:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_framerate’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:821:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
     if (GET_CODEC_FIELD(st->codec, codec_type) == CODEC_TYPE_VIDEO){
     ^~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:38:0:
/usr/local/cpffmpeg/include/libavformat/avformat.h:885:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:825:13: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
             rate = 1 / av_q2d(GET_CODEC_FIELD(st->codec, time_base));
             ^~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:38:0:
/usr/local/cpffmpeg/include/libavformat/avformat.h:885:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_framewidth’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:901:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
     return GET_CODEC_FIELD(st->codec, width);
     ^~~~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:38:0:
/usr/local/cpffmpeg/include/libavformat/avformat.h:885:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_frameheight’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:929:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
     return GET_CODEC_FIELD(st->codec, height);
     ^~~~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:38:0:
/usr/local/cpffmpeg/include/libavformat/avformat.h:885:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_codec_name’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1104:29: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘codec_name’; did you mean ‘codec_type’?
     } else if (decoder_ctx->codec_name[0] != '\0') {
                             ^~~~~~~~~~
                             codec_type
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1105:35: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘codec_name’; did you mean ‘codec_type’?
         codec_name = decoder_ctx->codec_name;
                                   ^~~~~~~~~~
                                   codec_type
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_read_av_frame’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1360:13: warning: ‘avcodec_decode_video2’ is deprecated [-Wdeprecated-declarations]
             avcodec_decode_video2(decoder_ctx, frame, &got_frame, &packet);
             ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:37:0:
/usr/local/cpffmpeg/include/libavcodec/avcodec.h:4824:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^~~~~~~~~~~~~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1365:17: warning: ‘av_free_packet’ is deprecated [-Wdeprecated-declarations]
                 av_free_packet(&packet);
                 ^~~~~~~~~~~~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:37:0:
/usr/local/cpffmpeg/include/libavcodec/avcodec.h:4469:6: note: declared here
 void av_free_packet(AVPacket *pkt);
      ^~~~~~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1371:9: warning: ‘av_free_packet’ is deprecated [-Wdeprecated-declarations]
         av_free_packet(&packet);
         ^~~~~~~~~~~~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:37:0:
/usr/local/cpffmpeg/include/libavcodec/avcodec.h:4469:6: note: declared here
 void av_free_packet(AVPacket *pkt);
      ^~~~~~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_av_frame’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1408:47: warning: passing argument 2 of ‘_php_open_movie_file’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
             _php_open_movie_file(ffmovie_ctx, _php_get_filename(ffmovie_ctx));
                                               ^~~~~~~~~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:323:12: note: expected ‘char *’ but argument is of type ‘const char *’
 static int _php_open_movie_file(ff_movie_context *ffmovie_ctx,
            ^~~~~~~~~~~~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_ff_frame’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1493:9: warning: ‘avpicture_alloc’ is deprecated [-Wdeprecated-declarations]
         avpicture_alloc((AVPicture*)ff_frame->av_frame, ff_frame->pixel_format,
         ^~~~~~~~~~~~~~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:37:0:
/usr/local/cpffmpeg/include/libavcodec/avcodec.h:5479:5: note: declared here
 int avpicture_alloc(AVPicture *picture, enum AVPixelFormat pix_fmt, int width, int height);
     ^~~~~~~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1499:25: warning: passing argument 1 of ‘av_image_copy’ from incompatible pointer type [-Wincompatible-pointer-types]
         av_picture_copy((AVPicture*)ff_frame->av_frame,
                         ^
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:81:19: note: in definition of macro ‘av_picture_copy’
     av_image_copy(dst->data, dst->linesize, (const uint8_t **)src->data,    \
                   ^~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:41:0:
/usr/local/cpffmpeg/include/libavutil/imgutils.h:119:6: note: expected ‘uint8_t ** {aka unsigned char **}’ but argument is of type ‘AVPicture * {aka struct AVPicture *}’
 void av_image_copy(uint8_t *dst_data[4], int dst_linesizes[4],
      ^~~~~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1499:25: warning: passing argument 2 of ‘av_image_copy’ from incompatible pointer type [-Wincompatible-pointer-types]
         av_picture_copy((AVPicture*)ff_frame->av_frame,
                         ^
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:81:30: note: in definition of macro ‘av_picture_copy’
     av_image_copy(dst->data, dst->linesize, (const uint8_t **)src->data,    \
                              ^~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:41:0:
/usr/local/cpffmpeg/include/libavutil/imgutils.h:119:6: note: expected ‘int *’ but argument is of type ‘AVPicture * {aka struct AVPicture *}’
 void av_image_copy(uint8_t *dst_data[4], int dst_linesizes[4],
      ^~~~~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1500:25: warning: passing argument 4 of ‘av_image_copy’ from incompatible pointer type [-Wincompatible-pointer-types]
                         (AVPicture*)frame, ff_frame->pixel_format,
                         ^
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:82:19: note: in definition of macro ‘av_picture_copy’
                   src->linesize, fmt, width, height)
                   ^~~
In file included from /usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:41:0:
/usr/local/cpffmpeg/include/libavutil/imgutils.h:119:6: note: expected ‘const int *’ but argument is of type ‘AVPicture * {aka struct AVPicture *}’
 void av_image_copy(uint8_t *dst_data[4], int dst_linesizes[4],
      ^~~~~~~~~~~~~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘zif_ffmpeg_movie_list’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1661:72: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘filename’
          add_index_string(return_value, 1000*i, ffmovie_ctx->fmt_ctx->filename);
                                                                     ^~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:1668:72: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘filename’
          add_index_string(return_value, 1000*i, ffmovie_ctx->fmt_ctx->filename);
                                                                     ^~
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c: In function ‘_php_get_filename’:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:269:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
At top level:
/usr/local/src/php8-build/php-8.3.7/ffmpeg-php/php7-ffmpeg-main/ffmpeg_movie.c:191:26: warning: ‘_php_get_ffmovie_ctx’ defined but not used [-Wunused-function]
 static ff_movie_context* _php_get_ffmovie_ctx()
                          ^~~~~~~~~~~~~~~~~~~~
Makefile:213: recipe for target 'ffmpeg_movie.lo' failed
make: *** [ffmpeg_movie.lo] Error 1

**Comment by budgierless** [comment]
this is on ubuntu 18.04.6 with php 8.3.7 using ffmpeg version N-94168-g0f39ef4db2-syslint

**Comment by budgierless** [comment]
please advise.
